
-- 3. CREAR UNA TABLA

CREATE TABLE IF NOT EXISTS Triangulo (
  idTriangulo INTEGER     NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cateto1     DOUBLE  NOT NULL,
  cateto2     DOUBLE  NOT NULL,
              
);

-- 4. MOSTRAR LAS TABLAS DE UNA BASE DE DATOS

SHOW TABLES;

-- 5. DESCRBIR UNA TABLE

DESCRIBE Triangulo;

-- 6. INSERTAR REGISTRO EN UNA TABLA

INSERT INTO triangulo(cateto1,cateto2) VALUES(12.1,10.5);

-- 7. MOSTRAR TODOS LOS REGISTROS DE UNA TABLA

SELECT * FROM Triangulo;
